# Generated by Django 2.0.8 on 2018-09-29 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('book_lending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lent', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_returned', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'book_lending',
            },
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='bookstatus',
            table='book_status',
        ),
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
        migrations.AlterModelTable(
            name='peoplestatus',
            table='people_status',
        ),
        migrations.AddField(
            model_name='booklending',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_lending.Book'),
        ),
        migrations.AddField(
            model_name='booklending',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_lending.People'),
        ),
    ]
