# Generated by Django 2.0.8 on 2018-09-29 12:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('book_lending', '0002_auto_20180929_1758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booklending',
            table='booklending',
        ),
        migrations.AlterModelTable(
            name='bookstatus',
            table='bookstatus',
        ),
        migrations.AlterModelTable(
            name='peoplestatus',
            table='peoplestatus',
        ),
    ]
